import Head from "next/head";
// import Image from "next/image";
import { signIn } from "next-auth/react"

import { Layout, Button } from "antd";
const { Content } = Layout;

const contentStyle = {
  textAlign: "center",
  minHeight: 120,
  lineHeight: "120px",
  color: "#fff",
  backgroundColor: "#108ee9",
  position: "relative",
  display: "flex",
  flexDirection: "column",
  justifyContent: "center",
  alignItems: "center",
};

const layoutContent = {
  minHeight: "100vh",
}

let title = "LOGIN CREDENTIALS"
// const { useToken } = theme;

export default function Home() {
  // const { token } = useToken();
  return (
    <>
      <Head>
        <title>{title}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

    
      <Layout style={layoutContent}>
        <Content style={contentStyle}>
          <Button onClick={()=> signIn()}>SIGN WITH CREDENTIALS</Button>
          <Button onClick={()=> signIn("google")}>SIGN WITH GOOGLE</Button>

        </Content>
      </Layout>
    </>
  )
}

