import Head from "next/head";
import { Layout, Menu} from "antd";
import PropTypes from "prop-types";
import Header from "./Header";
import { useState } from 'react';
import { useSession, signOut} from "next-auth/react";
import { useRouter } from "next/router";
import Link from "next/link";
import {
  MessageOutlined 
} from "@ant-design/icons";


const { Content, Sider } = Layout;
const siderStyle= {
  minHeight: "100vh",
  boxShadow: "0px 2px 8px rgba(0, 0, 0, 0.15)",
  overflow: "auto",
}

const items = [
  {
    icon:<MessageOutlined />,
    label: 'FD TALK',
    key: "talk1",
    children: [
          {
            label: "Group",
            key: '/group',
            link: "/group"
          },
          {
            label: 'Topic report',
            key: '/topic-report',
            link: "/topic-report"
          },
          {
            label: 'Talk report',
            key: '/talk-report',
            link: "/talk-report"
          }
        ],
  }
];


const LayoutBody = ({children, title, subtitle})=>{

  const router= useRouter()
  const { status, data:session } = useSession({
    required: true,
    onUnauthenticated() {
      // The user is not authenticated, handle it here.
      router.push("/")
    },
  })


  const handleClick = (e) => {
    router.push(`${process.env.NEXT_PUBLIC_HOST_LOCAL}${e.item.props.link}`)
  };
 // CLIENT SIDE RENDERING
 if (status === "loading") {
  return "Loading or not authenticated..."
}

  return (
    <>
      <Head>
        <title>{title}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <Sider
        theme="light"
        style={siderStyle}
        >
          <div justify="center" style={{padding: "1rem"}}>
					  <img width={120} src="https://s3.ap-southeast-1.amazonaws.com/assets.femaledaily.com/web-assets/icon/logo-fd.svg" alt="logo" />
          </div>
          <Menu 
            defaultOpenKeys={['talk1']}
            onClick={handleClick}
            defaultSelectedKeys={['/group']}
            mode="inline"
            selectedKeys={[router.pathname]}
            items={items}
          />
        </Sider>
        <Layout>
          <Header subtitle={subtitle} session={session} signOut={signOut}></Header>
          <Content>{children}</Content>
        </Layout>
      </Layout>
    </>

  );
};

LayoutBody.propTypes = {
  children: PropTypes.node.isRequired,
  title: PropTypes.node.isRequired,
  subtitle: PropTypes.string.isRequired

};
LayoutBody.defaultProps = {
  title: "Dashboard Belajar"
};


export default LayoutBody;